# Generated by Django 5.2.1 on 2025-05-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin_data',
            name='name',
            field=models.CharField(default='nitin', max_length=50),
            preserve_default=False,
        ),
    ]
