# Generated by Django 5.2.1 on 2025-05-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_appointment',
            name='blood_group',
            field=models.CharField(choices=[('A+ (A Positive)', 'A+ (A Positive)'), ('A− (A Negative)', 'A− (A Negative)'), ('B+ (B Positive)', 'B+ (B Positive)'), ('B− (B Negative)', 'B− (B Negative)'), ('AB+ (AB Positive)', 'AB+ (AB Positive)'), ('AB− (AB Negative)', 'AB− (AB Negative)'), ('O+ (O Positive)', 'O+ (O Positive)'), ('B+ (B Positive)', 'O− (O Negative)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='patient_appointment',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology'), ('Dermatology', 'Dermatology'), ('Urology', 'Urology'), ('ENT', 'ENT'), ('Radiology', 'Radiology'), ('Emergency Medicine', 'Emergency Medicine'), ('General Surgery', 'General Surgery'), ('Nephrology', 'Nephrology'), ('Gastroenterology', 'Gastroenterology'), ('Pulmonology', 'Pulmonology'), ('Ophthalmology', 'Ophthalmology'), ('Psychiatry', 'Psychiatry'), ('Pathology', 'Pathology'), ('Dentistry', 'Dentistry'), ('Physiotherapy / Rehabilitation', 'Physiotherapy / Rehabilitation'), ('Obstetrics', 'Obstetrics'), ('Endocrinology', 'Endocrinology')], max_length=128),
        ),
    ]
