# Generated by Django 5.2.1 on 2025-06-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_appointment_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_signup',
            name='password',
            field=models.CharField(default='true', max_length=50),
            preserve_default=False,
        ),
    ]
