# Generated by Django 5.2.1 on 2025-06-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_signup_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_appointment',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+ (A Positive)'), ('A-', 'A- (A Negative)'), ('B+', 'B+ (B Positive)'), ('B-', 'B- (B Negative)'), ('AB+', 'AB+ (AB Positive)'), ('AB-', 'AB- (AB Negative)'), ('O+', 'O+ (O Positive)'), ('O-', 'O- (O Negative)')], max_length=128),
        ),
    ]
