# Generated by Django 5.2.1 on 2025-11-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patient_signup_created_at_patient_signup_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_signup',
            name='Contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
